### PR TITLE
Changed occurrences of 'VERSION' to 'version' to prevent conflict wit…

### PR DESCRIPTION
**Pull request by psavery**
…h a new avogadro macro called 'VERSION'

### CODE REVIEW

**Comment by dlonie** [comment]
LGTM. Can you push this to master as well?

**Comment by dlonie** [comment]
We should probably get rid of stable and just use master, since it isn't really needed anymore...

**Comment by psavery** [comment]
Just sent in the pull request!

**Comment by psavery** [comment]
I had to get avogadro to make a few changes on their side for the
compatibility as well. They had an update recently that caused some issues
for external plugins like ours. There are a LOT more warnings now when
using certain versions of g++ that are caused by Eigen3. But they aren't an
issue as far as I can tell. They occur when compiling avogadro as well.

**Pull request merged**
