### PR TITLE
Update xtalcomp.cpp

### PR DESCRIPTION
**Pull request by psavery**

### CODE REVIEW

**Comment by dlonie** [comment]
I'll merge this, but keep in mind that each commit should be in a compilable state -- no need to put each file into a separate commit/branch/PR, they can all be committed together.

**Comment by psavery** [comment]
Yeah I looked for a while to try to figure out how to commit them together with the GUI on the website, and I couldn't find it... I think I just need to familiarze myself more with github

**Comment by dlonie** [comment]
I don't think you can on the website - you have to use git on the command
line with a local repo. `git gui` is a good tool for building up commits
from a modified repo.

**Comment by psavery** [comment]
I see that now. I've also been reading git tutorials and watching videos, and I understand a lot better how it all works. I'm definitely gonna be using git a lot more now! There are so many useful benefits!

**Pull request merged**
